name: ottu_flutter_sdk
description: A flutter plugin for ottu payment sdk project. This plugin allows developers to use ottu ios sdk on any flutter project, it gives the developer access to the payment delegate too.
version: 0.0.1+9
homepage: https://ottu.com/

environment:
  sdk: '>=1.19.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  json_serializable: ^3.5.1
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.2

flutter:

  plugin:
    platforms:
      ios:
        pluginClass: OttuFlutterSdkPlugin


